### ISSUE TITLE
where is code

### ISSUE THREAD

**Issue by Sandy4321** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#1]
thanks a lot for this great paper!!!!
per your paper
": A simple graph-based algorithm which implements a random
walk between users and items [8]."
may you help to find code location  in your  repo  for this  in this graph-based algorithm [8]

**Comment by Sandy4321** [comment]
meaning how to run this graph-based algorithm [8] from 0 to end using only Python and data sets from paper 
by the way can it be done on Windows computer and without Matlab
as written
For all baseline algorithms and datasets, we determined the optimal
parameters via Bayesian search [1] using the implementation
of Scikit-Optimize6. We explored 35 cases for each algorithm,
where the first 5 were used for the initial random points. We considered
neighborhood sizes k from 5 to 800; the shrink term h was
between 0 and 1000; and  and  took real values between 0 and 2.

**Comment by MaurizioFD** [comment]
Hi,

You will find an example on how to run both the deep learning algorithm and the baselines by looking at "run_KDD_15_CollaborativeDL.py".

The source code I am using is the original one provided by the authors so it is written in Matlab and that is the only version I have.
