### ISSUE TITLE
Can you add ratings (floats) to the ICM or do they have to be binarized?

### ISSUE THREAD

**Issue by ThomasAger** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#10]
Hey, this repository is great. I was just wondering if it is possible to add ICM values that are not binary, for example ratings, or if that will not be compatible with the methods in the repository. Thanks for any help.

**Comment by MaurizioFD** [comment]
Hi, thank you!

The code that is used to compute the similarity is the same for ICM and URM, and it supports real valued data. As you can see in the ItemKNNCBF the ICM can be weighted, which generates non-binary data.

**Comment by ThomasAger** [comment]
Thanks!
