### ISSUE TITLE
[ASK] When I run "run_WWW_17_NeuMF.py" script the execution didn't perform over the 6th epoch

### ISSUE THREAD

**Issue by TheAnswer96** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#12]
Hi, first of all I would like to congratulate for your amazing work. 

I have tried to use "run_WWW_17_NeuMF.py" script to get Neural Collaborative Filtering results but when the code was running it perfomed only the first 5 epochs. In particular the 6th epoch after two hours isn't completed. I ran the code without making any changes on my laptop that install an I7-8750H and a NVIDIA GTX 1070.

Does anyone know if it is an usual situation?
Do you think these are hardware issues?
Thank you very much for your help.
Have a nice day.

**Comment by MaurizioFD** [comment]
Hi,
Thank you, I am glad you foundo our work useful!

So, I checked the data I had and I see that on a NVIDIA Tesla V100 NeuMF on Movielens should complete its training in slightly more than 4 hours, while on Pinterests in almost 2 days.

If you have not changed the order of the datasets, then you are running it on Movielens. After epoch 5 there is the validation step, which required (on that GPU) around 5 minutes. 

Just a couple of trivial questions...
Do you see any indication of progress in the validation step or does the console get stuck at "epoch 5 complete"?
When the script is stuck do you see the CPU or GPU working?
Are you sure that the NVIDIA GPU is being used and not the CPU alone or the Intel GPU?

**Comment by TheAnswer96** [comment]
I noticed that the CPU is the only one working, so I tried running it on the GPU but I'm having problems finding a working method to do it.
Can you point me in the right direction?

**Comment by MaurizioFD** [comment]
Ok so, assuming you have the GPU correctly installed, you will need in your environment the GPU version of some of the packages. If you haven't I suggest you create a new environment and follow the "installation" section of the readme file.

If you already installed the GPU packages correctly, then you may need to set your keras/tensorflow to use the GPU device (which they should do automatically actually). I am not sure whether there is a better way, but I know of an environment variable you can set within python:

import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

With "0" meaning which device you want to use.

**Comment by TheAnswer96** [comment]
We were able to use the GPU now and we're running the tests right now, so thanks for your help.
If you don't mind I'd like to ask you one more thing: can you give us some details about the formatting of the dataset used for the tests?

**Comment by MaurizioFD** [comment]
Ok great.

The data is encoded in a scipy sparse matrix containing the interactions (either implicit or not). The shape is |n users|x|n items|. The format (CSR, CSC, COO) of input is not important as the code handles/checks that automatically.

In the "Data_manager" folder you can find some examples of data readers for common datasets.

**Comment by TheAnswer96** [comment]
Really thanks for helping. 
I'd like to congratulate again for this work!
