### ISSUE TITLE
HitRate formula

### ISSUE THREAD

**Issue by dev-rinchin** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#19]
Hi!
I'm wondering what formula you use to calculate the HitRate?
In the code I see this: https://github.com/MaurizioFD/RecSys2019_DeepLearning_Evaluation/blob/c173c9688c12e8b2866ac5f707e555faf811996f/Base/Evaluation/Evaluator.py#L339
it means "number of hidden true positives in the top-n recommendation list" and is equal to precision@K * K.

Thank you!

**Comment by MaurizioFD** [comment]
Hello,

Yes it simply computes the average number of correct recommendations per user, so it can be >1. It is equivalent to precision@k*k assuming all recommendation lists have the same length.

**Comment by dev-rinchin** [comment]
@MaurizioFD thanks for the answer!

What about the HitRate formula used in your papers? I haven't seen values > 1.

Also in paper [A Troubling Analysis of Reproducibility and Progress in Recommender Systems Research](https://arxiv.org/pdf/1911.07698.pdf) the HitRate formula described as "The Hit Rate measures if a single hidden true positive was part of the top-n recommendation list", but in referenced [paper](https://www.ijcai.org/proceedings/2018/0509.pdf) the HitRate formula defined as (num hits at K) / (num relevant values from test).

**Comment by MaurizioFD** [comment]
The ambiguity stems probably from the fact that it is usually used when the data is split via leave-one-out, so only one correct recommendation per user is possible. The description in the paper referred to that evaluation procedure, that is why it makes explicit reference to the single true positive.
In a random holdout setting where more than one correct recommendation exist then you have potentially values >1.
