### ISSUE TITLE
`update_count` in MultVAE

### ISSUE THREAD

**Issue by tohtsky** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#2]
First of all, thank you for this amazing project! This is so helpful to determine which algorithm fits best for given data!!
 
I have a question regarding `MultiVAE_RecommenderWrapper`.
https://github.com/MaurizioFD/RecSys2019_DeepLearning_Evaluation/blob/57ab65ada8cf70ed4876b8d33850fd7bc548183c/Conferences/WWW/MultiVAE_our_interface/MultiVAE_RecommenderWrapper.py#L169-L176

In the above lines, it seems that at `update_count` is reset to 0, so I think the coefficient for the KL divergence term restarts from 0 at every beginning of an epoch. 
In the original paper and implementation, if I understand correctly, `update_count` should be kept across the epochs.

Anyway, thank you again for this work!

**Comment by MaurizioFD** [comment]
Thank you! I am glad you found our work interesting and useful. There is an extension on the way with additional algorithms and baselines!

Regarding your question, you are correct. I have updated the source code and checked the results, the conclusions reported in the paper are confirmed.

Thank you again.

**Comment by tohtsky** [comment]
Thank you for the response! 
> the conclusions reported in the paper are confirmed.
Glad to hear that.  It seems that Mult-VAE and Mult-DAE don't differ so much regarding the performance..

Can I ask you another question regarding `P3alphaRecommender`?
If I understand correctly, the score is computed as the matrix product of `user_profile_array` and `W_sparse` in `compute_score_item_based` of `BaseSimilarityMatrixRecommender`.
If so, doesn't `user_profile_array` have to be raised to the power of alpha too?
In the original paper of P3alpha, the authors say that they use the third power of $P_\alpha$.
(I don't think this difference will significantly change the performance, though.)

Anyway, thank you again and I'm looking forward to additional algorithms & baselines!

**Comment by MaurizioFD** [comment]
Consider that we are using early-stopping to select the number of epochs, which may further stabilize the model performance.

Regarding your question about P3alphaRecommender you are correct in that the user profile should be elevated at the power of alpha. However in this case the ratings are implicit in all experiments, therefore there is no numerical difference.

**Comment by tohtsky** [comment]
> However in this case the ratings are implicit 
Ah, didn't notice that all types of the data in the paper are implicit.  Sorry to bother you again.
Thank you again for this great work again!  (I've found that P3alpha outperforms DL-based algorithm on my dataset too, by the way...)
