### ISSUE TITLE
DataSplitter_k_fold is missing?

### ISSUE THREAD

**Issue by ThomasAger** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#5]
I ran "run_parameter_search.py" and received the following error:

`ModuleNotFoundError: No module named 'Data_manager.DataSplitter_k_fold'`

Does this mean that in the Data_manager folder, the DataSplitter_k_fold python file is missing?

**Comment by MaurizioFD** [comment]
Hi,

Yes it means that the data splitter in question is missing.
The script in this project was not meant to be ran by itself, the "main" it contains is only there to provide an example on how to use it. Its usage can be seen and tested running any of the various DL experiments in the root folder.

**Comment by ThomasAger** [comment]
Thanks, appreciate the fast response.
