### ISSUE TITLE
Does this repository support Windows?

### ISSUE THREAD

**Issue by ThomasAger** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#6]
I followed the installation instructions no problem on my Linux machine, but when following them on my Windows machine I got to this point:

```
sudo apt install gcc 
sudo apt-get install python3-dev
```

And could no longer progress, as I believe python3-dev is not available for Windows? If I try to run the "python run_compile_all_cython.py" file, then I get the following output log:

```
Compiling [1/1]: Compute_Similarity_Cython.pyx... FAIL: Command 'C:\ProgramData\Anaconda3\envs\DLevaluation\python.exe E:\Github\RecSys2019_DeepLearning_Evaluation-master/CythonCompiler/compile_script.py Compute_Similarity_Cython.pyx build_ext --inplace' returned non-zero exit status 1.
run_compile_all_cython: Compilation finished. FAILS 1/1.
Compilation log can be found here: './result_experiments/run_compile_all_cython.txt'
```

Appreciate any help.

**Comment by MaurizioFD** [comment]
Hi,
This repository does support Windows, since I used it on a Windows PC as well. Installing everything can be a bit problematic however.

To compile the Cython code you will need to install a C copiler like MinGW. Please have a look here and let me know if you find it helpful: https://github.com/cython/cython/wiki/InstallingOnWindows

**Comment by ThomasAger** [comment]
Thanks for the info. I tried installing cython with conda and that seems to be successful but I am still getting the aforementioned error. Do you know if this means that I have failed to install cython correctly, or if it is another unrelated error?

**Comment by MaurizioFD** [comment]
Most likely there is a problem with the compiler, Cython simply transforms the code into C and then a C compiler is called.  Try running the compilation command directly and see what the output error is: 
python CythonCompiler/compile_script.py Compute_Similarity_Cython.pyx build_ext --inplace

Alternatively you could install the Windows Subsystem for Linux, if your machine supports it. But I never used it.

**Comment by ThomasAger** [comment]
Well this is odd. When I am in my Anaconda environment for this project that has cython installed the output is not very informative.

```
running build_ext
cythoning Compute_Similarity_Cython.pyx to Compute_Similarity_Cython.c
error: E:\Github\RecSys2019_DeepLearning_Evaluation-master\Compute_Similarity_Cython.pyx
```

Is it possible that I could run the compilation script on Linux, then transfer the files to Windows?

**Comment by MaurizioFD** [comment]
Now that I think of it, the only thing to compile are the KNN similarities, but there is also a Python implementation of them. If you skip the compilation step the Similarity object will use the Python version transparently. It may be a bit slower depending on the similarity and the dataset.

Alternatively... Try to refer to the cython documentation I linked, there are a couple of commands you can run to see if the libraries are set up correctly, those should be more informative.

The compiled file is non-portable, so you cannot transfer it on a different OS.

**Comment by ThomasAger** [comment]
Thanks, I'll look into getting cython set-up correctly.
